### PR TITLE
adding Kubernetes YAML for deployment, service and ingress

### PR DESCRIPTION
**Pull request by danielhartnell**
> Note in order to land a PR you must conform to the requirements outlined in https://github.com/mozilla-iam/mozilla-iam/blob/master/GitHub-Security-Settings.md

Branch Protection Rules on master, and production branches are set as follows:
    Protect this branch
    Require pull request reviews before merging
    Require signed commits
    Include administrators
    Restrict who can push to this branch
        Include the teams which should be able to affect code (i.e. write, commit, push code)
        Do NOT include the teams that may not (such as issue managers, bots, etc.)

NOTE: "Restrict who can push to this branch" is effectively the control by which you may allow specific teams to write issues without being able to change code. This does not prevent these teams from contributing through pull-requests. It prevents these teams from merging code.

### CODE REVIEW

**Comment by gdestuynder** [comment]
i wonder if we should use tags instead of production branch. just leaving that here, feel free to ignore this comment for now if its not the right time

**Comment by danielhartnell** [comment]
@gdestuynder,

That works for me. I can manage that with Terraform / the `buildspec.yml`. I already tested this with the Dino Park repositories and we're able to auto deploy to a dev namespace for pushes to master and then push to staging and prod namespaces with tagged releases like "v1.0.0-staging".

I don't have to set that up in this k8s YAML though. In the CodeBuild job we can pass a namespace arg into this template rendering to deploy to the proper location.

**Comment by gdestuynder** [comment]
@andrewkrug just checking that'd youd be open to using tags for releases

**Comment by andrewkrug** [comment]
++ for tags all the way and also having one way that we release for all of IAM

**Comment by danielhartnell** [comment]
Thanks. Once this is merged I can work on a new buildspec in the CodeBuild job to test the tagged based workflow. I'll push the buildspec into this source repository after that's been tested.

**Pull request merged**
